name: "Build (& Push) Dockers"

on: # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master]
    paths:
      - "requirements/*"
      - "requirements.txt"
      - ".devcontainer/*"
      - "dockers/**"
      - ".github/workflows/docker-build.yml"
      - "setup.py"
  pull_request:
    branches: [master]
    paths:
      - "requirements/*"
      - "requirements.txt"
      - ".devcontainer/*"
      - "dockers/**"
      - ".github/workflows/docker-build.yml"
      - "setup.py"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  PUSH_DOCKERHUB: ${{ github.ref == 'refs/heads/master' || github.event_name != 'pull_request' }}

jobs:
  build-Devcontainer:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: env.PUSH_DOCKERHUB == 'true' && github.repository_owner == 'Lightning-AI'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (and Push) Devcontainer
        # publish master/release
        uses: docker/build-push-action@v5
        with:
          build-args: |
            VARIANT=${{ matrix.python }}
          file: .devcontainer/Dockerfile
          push: ${{ env.PUSH_DOCKERHUB }}
          tags: "pytorchlightning/torchmetrics:devcontainer-py${{ matrix.python }}"
        timeout-minutes: 50

  build-cuda:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # These are the base images for PL release docker images,
          #  so include at least all the combinations in release-dockers.yml.
          - { python: "3.9", pytorch: "1.10", cuda: "11.3.1", ubuntu: "20.04" }
          - { python: "3.9", pytorch: "1.11", cuda: "11.8.0", ubuntu: "22.04" }
          - { python: "3.9", pytorch: "1.13", cuda: "11.8.0", ubuntu: "22.04" }
          - { python: "3.10", pytorch: "2.0", cuda: "11.8.0", ubuntu: "22.04" }
          - { python: "3.10", pytorch: "2.0", cuda: "12.1.0", ubuntu: "22.04" }
          - { python: "3.11", pytorch: "2.1", cuda: "12.1.0", ubuntu: "22.04" }
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: env.PUSH_DOCKERHUB == 'true' && github.repository_owner == 'Lightning-AI'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (and Push) runner
        uses: docker/build-push-action@v5
        with:
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu }}
            PYTHON_VERSION=${{ matrix.python }}
            PYTORCH_VERSION=${{ matrix.pytorch }}
            CUDA_VERSION=${{ matrix.cuda }}
          file: dockers/ubuntu-cuda/Dockerfile
          push: ${{ env.PUSH_DOCKERHUB }}
          tags: "pytorchlightning/torchmetrics:ubuntu${{ matrix.ubuntu }}-cuda${{ matrix.cuda }}-py${{ matrix.python }}-torch${{ matrix.pytorch }}"
        timeout-minutes: 55
